### ISSUE TITLE
Add-path support

### ISSUE THREAD

**Issue by netixx** [bgpfix/bgpfix#2]
Hello,

I am trying to implement add-path capability negotiation implementing `caps.Cap` interface.

However I realized that more core work need to be done do support add-path, because the Reach and Unreach need to include a path ID attributes. 

Do you have any plan already to support add-path ?

**Comment by pforemski** [comment]
Hello, and thanks for your interest in this project!

Yes, add-path would require more work for the reasons you specified. I wish I could, but I'm not planning to support this (soon), given other priorities and because I personally consider add-path being incrementally deprecated or avoided in ISP practice. I would be happy to learn I'm wrong. Anyway, I'll put add-path on my todo list (to support reading older MRT files), but can't guarantee any timeline.

**Comment by netixx** [comment]
It's a very nice project :) 

In my case, we use add-path to be able to get more visibility on router BGP table in a BGP route-collector scenario.
This enables us to compute backup paths for example.

I submitted a draft PR with a first implementation. I see that it's working in my case (ie. with add-path), but still need to test it more.

**Comment by pforemski** [comment]
Thanks, I commented in the #3 PR.

BTW, I'll be presenting bgpipe (and bgpfix) at RIPE 88 at the Routing WG (https://ripe88.ripe.net/) in 2 weeks. Feel free to participate (possibly remotely) and ask questions / discuss if you'd like to. Happy hacking :)

**Comment by netixx** [comment]
I implemented the fixes you suggested.

I won't be able to go to RIPE, but maybe you'll see some of my colleagues from OVHcloud :) 
I wish you a good talk, and I will definitely watch the replay!

**Comment by pforemski** [comment]
Thank you so much @netixx!

I have merged your work and made some changes, ~~primarily enabling best-effort ADD_PATH parsing in case we deal with raw MRT files with UPDATEs only (and haven't seen the session negotiation with capabilities)~~.

I have also modified the JSON format when marshaling ADD_PATH prefixes, to avoid confusion with IPv6 addresses (that also use colons and digits).

Would you have time to have a look at #5 ?

**Comment by pforemski** [comment]
@netixx ADD_PATH support, based on your original contribution, has just been merged into main and released as v0.4.0 (see 85c46f19bddbc835ad72a1237290abc8c6669e35).

Closing for now, please let me know if you have more comments / feedback.

Thank you!
